---
# tasks file for while_true_do.sys_vm_guest

- name: Manage VM Guest Packages
  package:
    name: "{{ wtd_sys_vm_guest_package }}"
    state: "{{ wtd_sys_vm_guest_package_state }}"
  become: true
  tags:
    - vm
    - virtualization
    - guest
    - package
